version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_bank/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  django_container_gunicorn:
    image: django_test_image:1
    networks:
      - network
    secrets:
      - SECRET_KEY





networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:

secrets:
  SECRET_KEY:
    external: true
