# Generated by Django 3.2.8 on 2021-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_trant_Amt', models.IntegerField()),
                ('Edu_level', models.IntegerField()),
                ('Income', models.IntegerField()),
                ('Total_relationship_cnt', models.IntegerField()),
                ('Month_on_book', models.IntegerField()),
                ('Customer_age', models.IntegerField()),
                ('Contact_cnt_12', models.IntegerField()),
                ('Dependent_count', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
