# Generated by Django 3.2.8 on 2021-11-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='username',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
