# Generated by Django 3.2.9 on 2021-11-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churner', '0003_auto_20211110_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predresults',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.AlterField(
            model_name='predresults',
            name='Income_Category',
            field=models.IntegerField(null=True),
        ),
    ]
